Lisk Name Service
LiskHQ/lisk-sdk-examples pull request #115
Opened 2021-05-22 21:28 UTC by nazarhussain

This PR contains the PoC for the Lisk Name Service. 

- Able to register .lsk domains.
- Manage and update domain records.
- Able to resolve a domain to an account address.
- Able to reverse lookup an address for its domain.
- Use the domain names in the UI tools instead of account address.

2021-06-22 10:34 UTC, Tschakki requested changes
I suggested some updates in the README, otherwise LGTM.

2021-06-22 10:34 UTC, Tschakki commented on tutorials/lisk-name-service/README.md
> +cd lns-dashboard-plugin && npm i && npm build
```suggestion
cd lns-dashboard-plugin && npm i && npm run build
```

2021-06-22 10:34 UTC, Tschakki commented on tutorials/lisk-name-service/README.md
> +
```suggestion

## Access UI

Open http://localhost:8000/ in the browser to access the LNS dashboard.
```

2021-06-28 12:05 UTC, shuse2 approved these changes

2021-07-07 09:54 UTC, merged