Fix broken readme links - Closes #189
LiskHQ/lisk-sdk-examples pull request #190
Opened 2022-10-11 10:01 UTC by chris529

Fix broken links and add new links/descriptions for the Postboard, the Social recovery (SRS), and the LNS tutorial.

Closes #189

2022-10-21 12:22 UTC, Tschakki requested changes

2022-10-21 12:22 UTC, Tschakki commented on README.adoc
> +A blockchain application built with the Lisk SDK v5.
```suggestion
A blockchain application built with the Lisk SDK v3.
```

2022-10-21 12:22 UTC, Tschakki commented on README.adoc
>  At the moment, the `/archive` folder contains examples for Lisk SDK `v2`, `v3` and `v4`.
The `archive` folder has been removed, so please remove this statements as well.

2022-10-28 12:36 UTC, chris529 commented on README.adoc
>  At the moment, the `/archive` folder contains examples for Lisk SDK `v2`, `v3` and `v4`.
Done 👍

2022-10-31 16:06 UTC, Tschakki requested changes
Just a few suggestions to improve descriptions and fix link, rest LGTM :)

2022-10-31 16:06 UTC, Tschakki commented on README.adoc
> +=== link:tutorials/lns[Lisk Name Service]
```suggestion
=== link:tutorials/lisk-name-service[Lisk Name Service]
```

2022-10-31 16:06 UTC, Tschakki commented on README.adoc
>  A few transactions are also included.
```suggestion
Allows a user to create, transfer and purchase NFTs.
```

2022-10-31 16:06 UTC, Tschakki commented on README.adoc
> +It is also equipped with a basic react frontend app including the most common interactions.
```suggestion
It demonstrates the use of On-Chain and Off-Chain architecture by creating a custom module and a plugin for a sidechain client.

It is also equipped with a basic react frontend app including the most common interactions.
```

2022-11-01 09:14 UTC, TalhaMaliktz requested changes
Looks good :). Just some minor changes.

2022-11-01 09:14 UTC, TalhaMaliktz commented on README.adoc
>  A hello world application built with the Lisk SDK v5.
```suggestion
A hello world application built with the Lisk SDK v6.
```

2022-11-01 09:14 UTC, TalhaMaliktz commented on README.adoc
> +=== link:tutorials/social-recovery[Social Recovery]
```suggestion
=== link:tutorials/social-recovery[Social Recovery System (SRS)]
```

2022-11-01 09:14 UTC, TalhaMaliktz commented on README.adoc
> +A blockchain application built with the Lisk SDK v5.
```suggestion
A blockchain application built with the Lisk SDK v6.
```

2022-11-01 09:14 UTC, TalhaMaliktz commented on README.adoc
> +=== link:tutorials/lisk-name-service[Lisk Name Service]
```suggestion
=== link:tutorials/lisk-name-service[Lisk Name Service (LNS)]
```

2022-11-01 10:47 UTC, TalhaMaliktz approved these changes
LGTM 😊

2022-11-01 14:06 UTC, Tschakki requested changes
The example apps are not updated yet

2022-11-01 14:06 UTC, Tschakki commented on README.adoc
> +A hello world application built with the Lisk SDK v6.
```suggestion
A hello world application built with the Lisk SDK v5.
```

2022-11-01 14:06 UTC, Tschakki commented on README.adoc
> +A blockchain application built with the Lisk SDK v6.
```suggestion
A blockchain application built with the Lisk SDK v5.
```

2022-11-01 14:13 UTC, chris529 commented on README.adoc
> +A blockchain application built with the Lisk SDK v6.
OK,  No worries...Talha and I had a discussion about this, as we both were not sure whether to state V6 at this point. However, you are correct Mona, the original apps were created in v5, so we can always update this again, once v6 is released and the apps are updated. 👍

2022-11-02 08:44 UTC, Tschakki approved these changes
LGTM

2022-11-02 08:44 UTC, merged